import Dropdown from "react-bootstrap/Dropdown";

export var data = [
  [
    {
      SK_ID_CURR: 100002,
      TARGET: 1,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 202500.0,
      AMT_CREDIT: 406597.5,
      AMT_ANNUITY: 24700.5,
    },
    {
      SK_ID_CURR: 100003,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 270000.0,
      AMT_CREDIT: 1293502.5,
      AMT_ANNUITY: 35698.5,
    },
    {
      SK_ID_CURR: 100004,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 67500.0,
      AMT_CREDIT: 135000.0,
      AMT_ANNUITY: 6750.0,
    },
    {
      SK_ID_CURR: 100006,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 135000.0,
      AMT_CREDIT: 312682.5,
      AMT_ANNUITY: 29686.5,
    },
    {
      SK_ID_CURR: 100007,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 121500.0,
      AMT_CREDIT: 513000.0,
      AMT_ANNUITY: 21865.5,
    },
    {
      SK_ID_CURR: 100008,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 99000.0,
      AMT_CREDIT: 490495.5,
      AMT_ANNUITY: 27517.5,
    },
    {
      SK_ID_CURR: 100009,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 171000.0,
      AMT_CREDIT: 1560726.0,
      AMT_ANNUITY: 41301.0,
    },
    {
      SK_ID_CURR: 100010,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 360000.0,
      AMT_CREDIT: 1530000.0,
      AMT_ANNUITY: 42075.0,
    },
    {
      SK_ID_CURR: 100011,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 112500.0,
      AMT_CREDIT: 1019610.0,
      AMT_ANNUITY: 33826.5,
    },
    {
      SK_ID_CURR: 100012,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 135000.0,
      AMT_CREDIT: 405000.0,
      AMT_ANNUITY: 20250.0,
    },
    {
      SK_ID_CURR: 100014,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 112500.0,
      AMT_CREDIT: 652500.0,
      AMT_ANNUITY: 21177.0,
    },
    {
      SK_ID_CURR: 100015,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 38419.155,
      AMT_CREDIT: 148365.0,
      AMT_ANNUITY: 10678.5,
    },
    {
      SK_ID_CURR: 100016,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 67500.0,
      AMT_CREDIT: 80865.0,
      AMT_ANNUITY: 5881.5,
    },
    {
      SK_ID_CURR: 100017,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 225000.0,
      AMT_CREDIT: 918468.0,
      AMT_ANNUITY: 28966.5,
    },
    {
      SK_ID_CURR: 100018,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 189000.0,
      AMT_CREDIT: 773680.5,
      AMT_ANNUITY: 32778.0,
    },
    {
      SK_ID_CURR: 100019,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 157500.0,
      AMT_CREDIT: 299772.0,
      AMT_ANNUITY: 20160.0,
    },
    {
      SK_ID_CURR: 100020,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 108000.0,
      AMT_CREDIT: 509602.5,
      AMT_ANNUITY: 26149.5,
    },
    {
      SK_ID_CURR: 100021,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 81000.0,
      AMT_CREDIT: 270000.0,
      AMT_ANNUITY: 13500.0,
    },
    {
      SK_ID_CURR: 100022,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 112500.0,
      AMT_CREDIT: 157500.0,
      AMT_ANNUITY: 7875.0,
    },
    {
      SK_ID_CURR: 100023,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 90000.0,
      AMT_CREDIT: 544491.0,
      AMT_ANNUITY: 17563.5,
    },
    {
      SK_ID_CURR: 100024,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 135000.0,
      AMT_CREDIT: 427500.0,
      AMT_ANNUITY: 21375.0,
    },
    {
      SK_ID_CURR: 100025,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 202500.0,
      AMT_CREDIT: 1132573.5,
      AMT_ANNUITY: 37561.5,
    },
    {
      SK_ID_CURR: 100026,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 450000.0,
      AMT_CREDIT: 497520.0,
      AMT_ANNUITY: 32521.5,
    },
    {
      SK_ID_CURR: 100027,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 83250.0,
      AMT_CREDIT: 239850.0,
      AMT_ANNUITY: 23850.0,
    },
    {
      SK_ID_CURR: 100029,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 2,
      AMT_INCOME_TOTAL: 135000.0,
      AMT_CREDIT: 247500.0,
      AMT_ANNUITY: 12703.5,
    },
    {
      SK_ID_CURR: 100030,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 90000.0,
      AMT_CREDIT: 225000.0,
      AMT_ANNUITY: 11074.5,
    },
    {
      SK_ID_CURR: 100031,
      TARGET: 1,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 112500.0,
      AMT_CREDIT: 979992.0,
      AMT_ANNUITY: 27076.5,
    },
    {
      SK_ID_CURR: 100032,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 112500.0,
      AMT_CREDIT: 327024.0,
      AMT_ANNUITY: 23827.5,
    },
    {
      SK_ID_CURR: 100033,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 270000.0,
      AMT_CREDIT: 790830.0,
      AMT_ANNUITY: 57676.5,
    },
    {
      SK_ID_CURR: 100034,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 90000.0,
      AMT_CREDIT: 180000.0,
      AMT_ANNUITY: 9000.0,
    },
    {
      SK_ID_CURR: 100035,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 292500.0,
      AMT_CREDIT: 665892.0,
      AMT_ANNUITY: 24592.5,
    },
    {
      SK_ID_CURR: 100036,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 112500.0,
      AMT_CREDIT: 512064.0,
      AMT_ANNUITY: 25033.5,
    },
    {
      SK_ID_CURR: 100037,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 90000.0,
      AMT_CREDIT: 199008.0,
      AMT_ANNUITY: 20893.5,
    },
    {
      SK_ID_CURR: 100039,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 360000.0,
      AMT_CREDIT: 733315.5,
      AMT_ANNUITY: 39069.0,
    },
    {
      SK_ID_CURR: 100040,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 135000.0,
      AMT_CREDIT: 1125000.0,
      AMT_ANNUITY: 32895.0,
    },
    {
      SK_ID_CURR: 100041,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 112500.0,
      AMT_CREDIT: 450000.0,
      AMT_ANNUITY: 44509.5,
    },
    {
      SK_ID_CURR: 100043,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 2,
      AMT_INCOME_TOTAL: 198000.0,
      AMT_CREDIT: 641173.5,
      AMT_ANNUITY: 23157.0,
    },
    {
      SK_ID_CURR: 100044,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 121500.0,
      AMT_CREDIT: 454500.0,
      AMT_ANNUITY: 15151.5,
    },
    {
      SK_ID_CURR: 100045,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 99000.0,
      AMT_CREDIT: 247275.0,
      AMT_ANNUITY: 17338.5,
    },
    {
      SK_ID_CURR: 100046,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 180000.0,
      AMT_CREDIT: 540000.0,
      AMT_ANNUITY: 27000.0,
    },
    {
      SK_ID_CURR: 100047,
      TARGET: 1,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 202500.0,
      AMT_CREDIT: 1193580.0,
      AMT_ANNUITY: 35028.0,
    },
    {
      SK_ID_CURR: 100048,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 202500.0,
      AMT_CREDIT: 604152.0,
      AMT_ANNUITY: 29196.0,
    },
    {
      SK_ID_CURR: 100049,
      TARGET: 1,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 135000.0,
      AMT_CREDIT: 288873.0,
      AMT_ANNUITY: 16258.5,
    },
    {
      SK_ID_CURR: 100050,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 108000.0,
      AMT_CREDIT: 746280.0,
      AMT_ANNUITY: 42970.5,
    },
    {
      SK_ID_CURR: 100051,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 202500.0,
      AMT_CREDIT: 661702.5,
      AMT_ANNUITY: 48280.5,
    },
    {
      SK_ID_CURR: 100052,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 90000.0,
      AMT_CREDIT: 180000.0,
      AMT_ANNUITY: 9000.0,
    },
    {
      SK_ID_CURR: 100053,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 202500.0,
      AMT_CREDIT: 305221.5,
      AMT_ANNUITY: 17649.0,
    },
    {
      SK_ID_CURR: 100054,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 99000.0,
      AMT_CREDIT: 260640.0,
      AMT_ANNUITY: 26838.0,
    },
    {
      SK_ID_CURR: 100055,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 130500.0,
      AMT_CREDIT: 1350000.0,
      AMT_ANNUITY: 37255.5,
    },
    {
      SK_ID_CURR: 100056,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 360000.0,
      AMT_CREDIT: 1506816.0,
      AMT_ANNUITY: 49927.5,
    },
    {
      SK_ID_CURR: 100058,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 54000.0,
      AMT_CREDIT: 135000.0,
      AMT_ANNUITY: 6750.0,
    },
    {
      SK_ID_CURR: 100059,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 540000.0,
      AMT_CREDIT: 675000.0,
      AMT_ANNUITY: 34596.0,
    },
    {
      SK_ID_CURR: 100060,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 76500.0,
      AMT_CREDIT: 454500.0,
      AMT_ANNUITY: 14661.0,
    },
    {
      SK_ID_CURR: 100061,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 2,
      AMT_INCOME_TOTAL: 225000.0,
      AMT_CREDIT: 314055.0,
      AMT_ANNUITY: 16164.0,
    },
    {
      SK_ID_CURR: 100062,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 81000.0,
      AMT_CREDIT: 675000.0,
      AMT_ANNUITY: 32472.0,
    },
    {
      SK_ID_CURR: 100063,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 180000.0,
      AMT_CREDIT: 837427.5,
      AMT_ANNUITY: 45558.0,
    },
    {
      SK_ID_CURR: 100064,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 67500.0,
      AMT_CREDIT: 298728.0,
      AMT_ANNUITY: 15381.0,
    },
    {
      SK_ID_CURR: 100068,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 81000.0,
      AMT_CREDIT: 247500.0,
      AMT_ANNUITY: 12375.0,
    },
    {
      SK_ID_CURR: 100069,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 360000.0,
      AMT_CREDIT: 640458.0,
      AMT_ANNUITY: 27265.5,
    },
    {
      SK_ID_CURR: 100070,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 540000.0,
      AMT_CREDIT: 1227901.5,
      AMT_ANNUITY: 46899.0,
    },
    {
      SK_ID_CURR: 100071,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 180000.0,
      AMT_CREDIT: 1663987.5,
      AMT_ANNUITY: 86989.5,
    },
    {
      SK_ID_CURR: 100072,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 180000.0,
      AMT_CREDIT: 1080000.0,
      AMT_ANNUITY: 44118.0,
    },
    {
      SK_ID_CURR: 100073,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 324000.0,
      AMT_CREDIT: 1130760.0,
      AMT_ANNUITY: 40189.5,
    },
    {
      SK_ID_CURR: 100075,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 112500.0,
      AMT_CREDIT: 95940.0,
      AMT_ANNUITY: 10462.5,
    },
    {
      SK_ID_CURR: 100076,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 180000.0,
      AMT_CREDIT: 315000.0,
      AMT_ANNUITY: 9679.5,
    },
    {
      SK_ID_CURR: 100077,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 180000.0,
      AMT_CREDIT: 1256400.0,
      AMT_ANNUITY: 40657.5,
    },
    {
      SK_ID_CURR: 100078,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 180000.0,
      AMT_CREDIT: 1035000.0,
      AMT_ANNUITY: 43983.0,
    },
    {
      SK_ID_CURR: 100079,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 225000.0,
      AMT_CREDIT: 270000.0,
      AMT_ANNUITY: 13500.0,
    },
    {
      SK_ID_CURR: 100080,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 157500.0,
      AMT_CREDIT: 450000.0,
      AMT_ANNUITY: 22500.0,
    },
    {
      SK_ID_CURR: 100081,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 180000.0,
      AMT_CREDIT: 450000.0,
      AMT_ANNUITY: 21109.5,
    },
    {
      SK_ID_CURR: 100082,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 2,
      AMT_INCOME_TOTAL: 180000.0,
      AMT_CREDIT: 450000.0,
      AMT_ANNUITY: 21109.5,
    },
    {
      SK_ID_CURR: 100083,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 103500.0,
      AMT_CREDIT: 573628.5,
      AMT_ANNUITY: 24435.0,
    },
    {
      SK_ID_CURR: 100084,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 2,
      AMT_INCOME_TOTAL: 225000.0,
      AMT_CREDIT: 495351.0,
      AMT_ANNUITY: 26140.5,
    },
    {
      SK_ID_CURR: 100085,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 157500.0,
      AMT_CREDIT: 755190.0,
      AMT_ANNUITY: 28894.5,
    },
    {
      SK_ID_CURR: 100086,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 135000.0,
      AMT_CREDIT: 675000.0,
      AMT_ANNUITY: 21775.5,
    },
    {
      SK_ID_CURR: 100087,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 202500.0,
      AMT_CREDIT: 1288350.0,
      AMT_ANNUITY: 37800.0,
    },
    {
      SK_ID_CURR: 100088,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 112500.0,
      AMT_CREDIT: 135000.0,
      AMT_ANNUITY: 6750.0,
    },
    {
      SK_ID_CURR: 100089,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 135000.0,
      AMT_CREDIT: 337761.0,
      AMT_ANNUITY: 15781.5,
    },
    {
      SK_ID_CURR: 100093,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 94500.0,
      AMT_CREDIT: 585000.0,
      AMT_ANNUITY: 28273.5,
    },
    {
      SK_ID_CURR: 100094,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 108000.0,
      AMT_CREDIT: 113760.0,
      AMT_ANNUITY: 5301.0,
    },
    {
      SK_ID_CURR: 100095,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 2,
      AMT_INCOME_TOTAL: 67500.0,
      AMT_CREDIT: 135000.0,
      AMT_ANNUITY: 6750.0,
    },
    {
      SK_ID_CURR: 100096,
      TARGET: 1,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 81000.0,
      AMT_CREDIT: 252000.0,
      AMT_ANNUITY: 14593.5,
    },
    {
      SK_ID_CURR: 100097,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 157500.0,
      AMT_CREDIT: 760225.5,
      AMT_ANNUITY: 30280.5,
    },
    {
      SK_ID_CURR: 100098,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Revolving loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 225000.0,
      AMT_CREDIT: 270000.0,
      AMT_ANNUITY: 13500.0,
    },
    {
      SK_ID_CURR: 100099,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 360000.0,
      AMT_CREDIT: 733315.5,
      AMT_ANNUITY: 41076.0,
    },
    {
      SK_ID_CURR: 100100,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 2,
      AMT_INCOME_TOTAL: 202500.0,
      AMT_CREDIT: 796396.5,
      AMT_ANNUITY: 38443.5,
    },
    {
      SK_ID_CURR: 100101,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 202500.0,
      AMT_CREDIT: 343377.0,
      AMT_ANNUITY: 22072.5,
    },
    {
      SK_ID_CURR: 100102,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 126000.0,
      AMT_CREDIT: 327024.0,
      AMT_ANNUITY: 10264.5,
    },
    {
      SK_ID_CURR: 100103,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 72000.0,
      AMT_CREDIT: 450000.0,
      AMT_ANNUITY: 16965.0,
    },
    {
      SK_ID_CURR: 100104,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 90000.0,
      AMT_CREDIT: 547344.0,
      AMT_ANNUITY: 30690.0,
    },
    {
      SK_ID_CURR: 100105,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 193500.0,
      AMT_CREDIT: 225000.0,
      AMT_ANNUITY: 23755.5,
    },
    {
      SK_ID_CURR: 100108,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 3,
      AMT_INCOME_TOTAL: 171000.0,
      AMT_CREDIT: 545040.0,
      AMT_ANNUITY: 31288.5,
    },
    {
      SK_ID_CURR: 100110,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 3,
      AMT_INCOME_TOTAL: 135000.0,
      AMT_CREDIT: 373140.0,
      AMT_ANNUITY: 25065.0,
    },
    {
      SK_ID_CURR: 100111,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 1,
      AMT_INCOME_TOTAL: 112500.0,
      AMT_CREDIT: 862560.0,
      AMT_ANNUITY: 27954.0,
    },
    {
      SK_ID_CURR: 100112,
      TARGET: 1,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 315000.0,
      AMT_CREDIT: 953460.0,
      AMT_ANNUITY: 64107.0,
    },
    {
      SK_ID_CURR: 100113,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "M",
      FLAG_OWN_CAR: "Y",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 76500.0,
      AMT_CREDIT: 135000.0,
      AMT_ANNUITY: 6696.0,
    },
    {
      SK_ID_CURR: 100114,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 135000.0,
      AMT_CREDIT: 284400.0,
      AMT_ANNUITY: 22599.0,
    },
    {
      SK_ID_CURR: 100115,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "N",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 90000.0,
      AMT_CREDIT: 315000.0,
      AMT_ANNUITY: 14683.5,
    },
    {
      SK_ID_CURR: 100116,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 243000.0,
      AMT_CREDIT: 900000.0,
      AMT_ANNUITY: 32017.5,
    },
    {
      SK_ID_CURR: 100118,
      TARGET: 0,
      NAME_CONTRACT_TYPE: "Cash loans",
      CODE_GENDER: "F",
      FLAG_OWN_CAR: "N",
      FLAG_OWN_REALTY: "Y",
      CNT_CHILDREN: 0,
      AMT_INCOME_TOTAL: 90000.0,
      AMT_CREDIT: 675000.0,
      AMT_ANNUITY: 26541.0,
    },
  ],
  [
    {
      PassengerId: 892,
      Pclass: 3,
      Name: "Kelly, Mr. James",
      Sex: "male",
      Age: 34.5,
      SibSp: 0,
      Parch: 0,
      Ticket: "330911",
      Fare: 7.8292,
      Cabin: "None",
    },
    {
      PassengerId: 893,
      Pclass: 3,
      Name: "Wilkes, Mrs. James (Ellen Needs)",
      Sex: "female",
      Age: 47.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "363272",
      Fare: 7.0,
      Cabin: "None",
    },
    {
      PassengerId: 894,
      Pclass: 2,
      Name: "Myles, Mr. Thomas Francis",
      Sex: "male",
      Age: 62.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "240276",
      Fare: 9.6875,
      Cabin: "None",
    },
    {
      PassengerId: 895,
      Pclass: 3,
      Name: "Wirz, Mr. Albert",
      Sex: "male",
      Age: 27.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "315154",
      Fare: 8.6625,
      Cabin: "None",
    },
    {
      PassengerId: 896,
      Pclass: 3,
      Name: "Hirvonen, Mrs. Alexander (Helga E Lindqvist)",
      Sex: "female",
      Age: 22.0,
      SibSp: 1,
      Parch: 1,
      Ticket: "3101298",
      Fare: 12.2875,
      Cabin: "None",
    },
    {
      PassengerId: 897,
      Pclass: 3,
      Name: "Svensson, Mr. Johan Cervin",
      Sex: "male",
      Age: 14.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "7538",
      Fare: 9.225,
      Cabin: "None",
    },
    {
      PassengerId: 898,
      Pclass: 3,
      Name: "Connolly, Miss. Kate",
      Sex: "female",
      Age: 30.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "330972",
      Fare: 7.6292,
      Cabin: "None",
    },
    {
      PassengerId: 899,
      Pclass: 2,
      Name: "Caldwell, Mr. Albert Francis",
      Sex: "male",
      Age: 26.0,
      SibSp: 1,
      Parch: 1,
      Ticket: "248738",
      Fare: 29.0,
      Cabin: "None",
    },
    {
      PassengerId: 900,
      Pclass: 3,
      Name: "Abrahim, Mrs. Joseph (Sophie Halaut Easu)",
      Sex: "female",
      Age: 18.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "2657",
      Fare: 7.2292,
      Cabin: "None",
    },
    {
      PassengerId: 901,
      Pclass: 3,
      Name: "Davies, Mr. John Samuel",
      Sex: "male",
      Age: 21.0,
      SibSp: 2,
      Parch: 0,
      Ticket: "A/4 48871",
      Fare: 24.15,
      Cabin: "None",
    },
    {
      PassengerId: 902,
      Pclass: 3,
      Name: "Ilieff, Mr. Ylio",
      Sex: "male",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "349220",
      Fare: 7.8958,
      Cabin: "None",
    },
    {
      PassengerId: 903,
      Pclass: 1,
      Name: "Jones, Mr. Charles Cresson",
      Sex: "male",
      Age: 46.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "694",
      Fare: 26.0,
      Cabin: "None",
    },
    {
      PassengerId: 904,
      Pclass: 1,
      Name: "Snyder, Mrs. John Pillsbury (Nelle Stevenson)",
      Sex: "female",
      Age: 23.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "21228",
      Fare: 82.2667,
      Cabin: "B45",
    },
    {
      PassengerId: 905,
      Pclass: 2,
      Name: "Howard, Mr. Benjamin",
      Sex: "male",
      Age: 63.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "24065",
      Fare: 26.0,
      Cabin: "None",
    },
    {
      PassengerId: 906,
      Pclass: 1,
      Name: "Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)",
      Sex: "female",
      Age: 47.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "W.E.P. 5734",
      Fare: 61.175,
      Cabin: "E31",
    },
    {
      PassengerId: 907,
      Pclass: 2,
      Name: "del Carlo, Mrs. Sebastiano (Argenia Genovesi)",
      Sex: "female",
      Age: 24.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "SC/PARIS 2167",
      Fare: 27.7208,
      Cabin: "None",
    },
    {
      PassengerId: 908,
      Pclass: 2,
      Name: "Keane, Mr. Daniel",
      Sex: "male",
      Age: 35.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "233734",
      Fare: 12.35,
      Cabin: "None",
    },
    {
      PassengerId: 909,
      Pclass: 3,
      Name: "Assaf, Mr. Gerios",
      Sex: "male",
      Age: 21.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "2692",
      Fare: 7.225,
      Cabin: "None",
    },
    {
      PassengerId: 910,
      Pclass: 3,
      Name: "Ilmakangas, Miss. Ida Livija",
      Sex: "female",
      Age: 27.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "STON/O2. 3101270",
      Fare: 7.925,
      Cabin: "None",
    },
    {
      PassengerId: 911,
      Pclass: 3,
      Name: 'Assaf Khalil, Mrs. Mariana (Miriam")"',
      Sex: "female",
      Age: 45.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "2696",
      Fare: 7.225,
      Cabin: "None",
    },
    {
      PassengerId: 912,
      Pclass: 1,
      Name: "Rothschild, Mr. Martin",
      Sex: "male",
      Age: 55.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "PC 17603",
      Fare: 59.4,
      Cabin: "None",
    },
    {
      PassengerId: 913,
      Pclass: 3,
      Name: "Olsen, Master. Artur Karl",
      Sex: "male",
      Age: 9.0,
      SibSp: 0,
      Parch: 1,
      Ticket: "C 17368",
      Fare: 3.1708,
      Cabin: "None",
    },
    {
      PassengerId: 914,
      Pclass: 1,
      Name: "Flegenheim, Mrs. Alfred (Antoinette)",
      Sex: "female",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "PC 17598",
      Fare: 31.6833,
      Cabin: "None",
    },
    {
      PassengerId: 915,
      Pclass: 1,
      Name: "Williams, Mr. Richard Norris II",
      Sex: "male",
      Age: 21.0,
      SibSp: 0,
      Parch: 1,
      Ticket: "PC 17597",
      Fare: 61.3792,
      Cabin: "None",
    },
    {
      PassengerId: 916,
      Pclass: 1,
      Name: "Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",
      Sex: "female",
      Age: 48.0,
      SibSp: 1,
      Parch: 3,
      Ticket: "PC 17608",
      Fare: 262.375,
      Cabin: "B57 B59 B63 B66",
    },
    {
      PassengerId: 917,
      Pclass: 3,
      Name: "Robins, Mr. Alexander A",
      Sex: "male",
      Age: 50.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "A/5. 3337",
      Fare: 14.5,
      Cabin: "None",
    },
    {
      PassengerId: 918,
      Pclass: 1,
      Name: "Ostby, Miss. Helene Ragnhild",
      Sex: "female",
      Age: 22.0,
      SibSp: 0,
      Parch: 1,
      Ticket: "113509",
      Fare: 61.9792,
      Cabin: "B36",
    },
    {
      PassengerId: 919,
      Pclass: 3,
      Name: "Daher, Mr. Shedid",
      Sex: "male",
      Age: 22.5,
      SibSp: 0,
      Parch: 0,
      Ticket: "2698",
      Fare: 7.225,
      Cabin: "None",
    },
    {
      PassengerId: 920,
      Pclass: 1,
      Name: "Brady, Mr. John Bertram",
      Sex: "male",
      Age: 41.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "113054",
      Fare: 30.5,
      Cabin: "A21",
    },
    {
      PassengerId: 921,
      Pclass: 3,
      Name: "Samaan, Mr. Elias",
      Sex: "male",
      Age: "None",
      SibSp: 2,
      Parch: 0,
      Ticket: "2662",
      Fare: 21.6792,
      Cabin: "None",
    },
    {
      PassengerId: 922,
      Pclass: 2,
      Name: "Louch, Mr. Charles Alexander",
      Sex: "male",
      Age: 50.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "SC/AH 3085",
      Fare: 26.0,
      Cabin: "None",
    },
    {
      PassengerId: 923,
      Pclass: 2,
      Name: "Jefferys, Mr. Clifford Thomas",
      Sex: "male",
      Age: 24.0,
      SibSp: 2,
      Parch: 0,
      Ticket: "C.A. 31029",
      Fare: 31.5,
      Cabin: "None",
    },
    {
      PassengerId: 924,
      Pclass: 3,
      Name: "Dean, Mrs. Bertram (Eva Georgetta Light)",
      Sex: "female",
      Age: 33.0,
      SibSp: 1,
      Parch: 2,
      Ticket: "C.A. 2315",
      Fare: 20.575,
      Cabin: "None",
    },
    {
      PassengerId: 925,
      Pclass: 3,
      Name: 'Johnston, Mrs. Andrew G (Elizabeth Lily" Watson)"',
      Sex: "female",
      Age: "None",
      SibSp: 1,
      Parch: 2,
      Ticket: "W./C. 6607",
      Fare: 23.45,
      Cabin: "None",
    },
    {
      PassengerId: 926,
      Pclass: 1,
      Name: "Mock, Mr. Philipp Edmund",
      Sex: "male",
      Age: 30.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "13236",
      Fare: 57.75,
      Cabin: "C78",
    },
    {
      PassengerId: 927,
      Pclass: 3,
      Name: 'Katavelas, Mr. Vassilios (Catavelas Vassilios")"',
      Sex: "male",
      Age: 18.5,
      SibSp: 0,
      Parch: 0,
      Ticket: "2682",
      Fare: 7.2292,
      Cabin: "None",
    },
    {
      PassengerId: 928,
      Pclass: 3,
      Name: "Roth, Miss. Sarah A",
      Sex: "female",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "342712",
      Fare: 8.05,
      Cabin: "None",
    },
    {
      PassengerId: 929,
      Pclass: 3,
      Name: "Cacic, Miss. Manda",
      Sex: "female",
      Age: 21.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "315087",
      Fare: 8.6625,
      Cabin: "None",
    },
    {
      PassengerId: 930,
      Pclass: 3,
      Name: "Sap, Mr. Julius",
      Sex: "male",
      Age: 25.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "345768",
      Fare: 9.5,
      Cabin: "None",
    },
    {
      PassengerId: 931,
      Pclass: 3,
      Name: "Hee, Mr. Ling",
      Sex: "male",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "1601",
      Fare: 56.4958,
      Cabin: "None",
    },
    {
      PassengerId: 932,
      Pclass: 3,
      Name: "Karun, Mr. Franz",
      Sex: "male",
      Age: 39.0,
      SibSp: 0,
      Parch: 1,
      Ticket: "349256",
      Fare: 13.4167,
      Cabin: "None",
    },
    {
      PassengerId: 933,
      Pclass: 1,
      Name: "Franklin, Mr. Thomas Parham",
      Sex: "male",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "113778",
      Fare: 26.55,
      Cabin: "D34",
    },
    {
      PassengerId: 934,
      Pclass: 3,
      Name: "Goldsmith, Mr. Nathan",
      Sex: "male",
      Age: 41.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "SOTON/O.Q. 3101263",
      Fare: 7.85,
      Cabin: "None",
    },
    {
      PassengerId: 935,
      Pclass: 2,
      Name: "Corbett, Mrs. Walter H (Irene Colvin)",
      Sex: "female",
      Age: 30.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "237249",
      Fare: 13.0,
      Cabin: "None",
    },
    {
      PassengerId: 936,
      Pclass: 1,
      Name: "Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)",
      Sex: "female",
      Age: 45.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "11753",
      Fare: 52.5542,
      Cabin: "D19",
    },
    {
      PassengerId: 937,
      Pclass: 3,
      Name: "Peltomaki, Mr. Nikolai Johannes",
      Sex: "male",
      Age: 25.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "STON/O 2. 3101291",
      Fare: 7.925,
      Cabin: "None",
    },
    {
      PassengerId: 938,
      Pclass: 1,
      Name: "Chevre, Mr. Paul Romaine",
      Sex: "male",
      Age: 45.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "PC 17594",
      Fare: 29.7,
      Cabin: "A9",
    },
    {
      PassengerId: 939,
      Pclass: 3,
      Name: "Shaughnessy, Mr. Patrick",
      Sex: "male",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "370374",
      Fare: 7.75,
      Cabin: "None",
    },
    {
      PassengerId: 940,
      Pclass: 1,
      Name: "Bucknell, Mrs. William Robert (Emma Eliza Ward)",
      Sex: "female",
      Age: 60.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "11813",
      Fare: 76.2917,
      Cabin: "D15",
    },
    {
      PassengerId: 941,
      Pclass: 3,
      Name: 'Coutts, Mrs. William (Winnie Minnie" Treanor)"',
      Sex: "female",
      Age: 36.0,
      SibSp: 0,
      Parch: 2,
      Ticket: "C.A. 37671",
      Fare: 15.9,
      Cabin: "None",
    },
    {
      PassengerId: 942,
      Pclass: 1,
      Name: "Smith, Mr. Lucien Philip",
      Sex: "male",
      Age: 24.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "13695",
      Fare: 60.0,
      Cabin: "C31",
    },
    {
      PassengerId: 943,
      Pclass: 2,
      Name: "Pulbaum, Mr. Franz",
      Sex: "male",
      Age: 27.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "SC/PARIS 2168",
      Fare: 15.0333,
      Cabin: "None",
    },
    {
      PassengerId: 944,
      Pclass: 2,
      Name: 'Hocking, Miss. Ellen Nellie""',
      Sex: "female",
      Age: 20.0,
      SibSp: 2,
      Parch: 1,
      Ticket: "29105",
      Fare: 23.0,
      Cabin: "None",
    },
    {
      PassengerId: 945,
      Pclass: 1,
      Name: "Fortune, Miss. Ethel Flora",
      Sex: "female",
      Age: 28.0,
      SibSp: 3,
      Parch: 2,
      Ticket: "19950",
      Fare: 263.0,
      Cabin: "C23 C25 C27",
    },
    {
      PassengerId: 946,
      Pclass: 2,
      Name: "Mangiavacchi, Mr. Serafino Emilio",
      Sex: "male",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "SC/A.3 2861",
      Fare: 15.5792,
      Cabin: "None",
    },
    {
      PassengerId: 947,
      Pclass: 3,
      Name: "Rice, Master. Albert",
      Sex: "male",
      Age: 10.0,
      SibSp: 4,
      Parch: 1,
      Ticket: "382652",
      Fare: 29.125,
      Cabin: "None",
    },
    {
      PassengerId: 948,
      Pclass: 3,
      Name: "Cor, Mr. Bartol",
      Sex: "male",
      Age: 35.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "349230",
      Fare: 7.8958,
      Cabin: "None",
    },
    {
      PassengerId: 949,
      Pclass: 3,
      Name: "Abelseth, Mr. Olaus Jorgensen",
      Sex: "male",
      Age: 25.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "348122",
      Fare: 7.65,
      Cabin: "F G63",
    },
    {
      PassengerId: 950,
      Pclass: 3,
      Name: "Davison, Mr. Thomas Henry",
      Sex: "male",
      Age: "None",
      SibSp: 1,
      Parch: 0,
      Ticket: "386525",
      Fare: 16.1,
      Cabin: "None",
    },
    {
      PassengerId: 951,
      Pclass: 1,
      Name: "Chaudanson, Miss. Victorine",
      Sex: "female",
      Age: 36.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "PC 17608",
      Fare: 262.375,
      Cabin: "B61",
    },
    {
      PassengerId: 952,
      Pclass: 3,
      Name: "Dika, Mr. Mirko",
      Sex: "male",
      Age: 17.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "349232",
      Fare: 7.8958,
      Cabin: "None",
    },
    {
      PassengerId: 953,
      Pclass: 2,
      Name: "McCrae, Mr. Arthur Gordon",
      Sex: "male",
      Age: 32.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "237216",
      Fare: 13.5,
      Cabin: "None",
    },
    {
      PassengerId: 954,
      Pclass: 3,
      Name: "Bjorklund, Mr. Ernst Herbert",
      Sex: "male",
      Age: 18.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "347090",
      Fare: 7.75,
      Cabin: "None",
    },
    {
      PassengerId: 955,
      Pclass: 3,
      Name: "Bradley, Miss. Bridget Delia",
      Sex: "female",
      Age: 22.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "334914",
      Fare: 7.725,
      Cabin: "None",
    },
    {
      PassengerId: 956,
      Pclass: 1,
      Name: "Ryerson, Master. John Borie",
      Sex: "male",
      Age: 13.0,
      SibSp: 2,
      Parch: 2,
      Ticket: "PC 17608",
      Fare: 262.375,
      Cabin: "B57 B59 B63 B66",
    },
    {
      PassengerId: 957,
      Pclass: 2,
      Name: "Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)",
      Sex: "female",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "F.C.C. 13534",
      Fare: 21.0,
      Cabin: "None",
    },
    {
      PassengerId: 958,
      Pclass: 3,
      Name: "Burns, Miss. Mary Delia",
      Sex: "female",
      Age: 18.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "330963",
      Fare: 7.8792,
      Cabin: "None",
    },
    {
      PassengerId: 959,
      Pclass: 1,
      Name: "Moore, Mr. Clarence Bloomfield",
      Sex: "male",
      Age: 47.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "113796",
      Fare: 42.4,
      Cabin: "None",
    },
    {
      PassengerId: 960,
      Pclass: 1,
      Name: "Tucker, Mr. Gilbert Milligan Jr",
      Sex: "male",
      Age: 31.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "2543",
      Fare: 28.5375,
      Cabin: "C53",
    },
    {
      PassengerId: 961,
      Pclass: 1,
      Name: "Fortune, Mrs. Mark (Mary McDougald)",
      Sex: "female",
      Age: 60.0,
      SibSp: 1,
      Parch: 4,
      Ticket: "19950",
      Fare: 263.0,
      Cabin: "C23 C25 C27",
    },
    {
      PassengerId: 962,
      Pclass: 3,
      Name: "Mulvihill, Miss. Bertha E",
      Sex: "female",
      Age: 24.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "382653",
      Fare: 7.75,
      Cabin: "None",
    },
    {
      PassengerId: 963,
      Pclass: 3,
      Name: "Minkoff, Mr. Lazar",
      Sex: "male",
      Age: 21.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "349211",
      Fare: 7.8958,
      Cabin: "None",
    },
    {
      PassengerId: 964,
      Pclass: 3,
      Name: "Nieminen, Miss. Manta Josefina",
      Sex: "female",
      Age: 29.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "3101297",
      Fare: 7.925,
      Cabin: "None",
    },
    {
      PassengerId: 965,
      Pclass: 1,
      Name: "Ovies y Rodriguez, Mr. Servando",
      Sex: "male",
      Age: 28.5,
      SibSp: 0,
      Parch: 0,
      Ticket: "PC 17562",
      Fare: 27.7208,
      Cabin: "D43",
    },
    {
      PassengerId: 966,
      Pclass: 1,
      Name: "Geiger, Miss. Amalie",
      Sex: "female",
      Age: 35.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "113503",
      Fare: 211.5,
      Cabin: "C130",
    },
    {
      PassengerId: 967,
      Pclass: 1,
      Name: "Keeping, Mr. Edwin",
      Sex: "male",
      Age: 32.5,
      SibSp: 0,
      Parch: 0,
      Ticket: "113503",
      Fare: 211.5,
      Cabin: "C132",
    },
    {
      PassengerId: 968,
      Pclass: 3,
      Name: "Miles, Mr. Frank",
      Sex: "male",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "359306",
      Fare: 8.05,
      Cabin: "None",
    },
    {
      PassengerId: 969,
      Pclass: 1,
      Name: "Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)",
      Sex: "female",
      Age: 55.0,
      SibSp: 2,
      Parch: 0,
      Ticket: "11770",
      Fare: 25.7,
      Cabin: "C101",
    },
    {
      PassengerId: 970,
      Pclass: 2,
      Name: "Aldworth, Mr. Charles Augustus",
      Sex: "male",
      Age: 30.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "248744",
      Fare: 13.0,
      Cabin: "None",
    },
    {
      PassengerId: 971,
      Pclass: 3,
      Name: "Doyle, Miss. Elizabeth",
      Sex: "female",
      Age: 24.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "368702",
      Fare: 7.75,
      Cabin: "None",
    },
    {
      PassengerId: 972,
      Pclass: 3,
      Name: "Boulos, Master. Akar",
      Sex: "male",
      Age: 6.0,
      SibSp: 1,
      Parch: 1,
      Ticket: "2678",
      Fare: 15.2458,
      Cabin: "None",
    },
    {
      PassengerId: 973,
      Pclass: 1,
      Name: "Straus, Mr. Isidor",
      Sex: "male",
      Age: 67.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "PC 17483",
      Fare: 221.7792,
      Cabin: "C55 C57",
    },
    {
      PassengerId: 974,
      Pclass: 1,
      Name: "Case, Mr. Howard Brown",
      Sex: "male",
      Age: 49.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "19924",
      Fare: 26.0,
      Cabin: "None",
    },
    {
      PassengerId: 975,
      Pclass: 3,
      Name: "Demetri, Mr. Marinko",
      Sex: "male",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "349238",
      Fare: 7.8958,
      Cabin: "None",
    },
    {
      PassengerId: 976,
      Pclass: 2,
      Name: "Lamb, Mr. John Joseph",
      Sex: "male",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "240261",
      Fare: 10.7083,
      Cabin: "None",
    },
    {
      PassengerId: 977,
      Pclass: 3,
      Name: "Khalil, Mr. Betros",
      Sex: "male",
      Age: "None",
      SibSp: 1,
      Parch: 0,
      Ticket: "2660",
      Fare: 14.4542,
      Cabin: "None",
    },
    {
      PassengerId: 978,
      Pclass: 3,
      Name: "Barry, Miss. Julia",
      Sex: "female",
      Age: 27.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "330844",
      Fare: 7.8792,
      Cabin: "None",
    },
    {
      PassengerId: 979,
      Pclass: 3,
      Name: "Badman, Miss. Emily Louisa",
      Sex: "female",
      Age: 18.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "A/4 31416",
      Fare: 8.05,
      Cabin: "None",
    },
    {
      PassengerId: 980,
      Pclass: 3,
      Name: "O'Donoghue, Ms. Bridget",
      Sex: "female",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "364856",
      Fare: 7.75,
      Cabin: "None",
    },
    {
      PassengerId: 981,
      Pclass: 2,
      Name: "Wells, Master. Ralph Lester",
      Sex: "male",
      Age: 2.0,
      SibSp: 1,
      Parch: 1,
      Ticket: "29103",
      Fare: 23.0,
      Cabin: "None",
    },
    {
      PassengerId: 982,
      Pclass: 3,
      Name: "Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)",
      Sex: "female",
      Age: 22.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "347072",
      Fare: 13.9,
      Cabin: "None",
    },
    {
      PassengerId: 983,
      Pclass: 3,
      Name: "Pedersen, Mr. Olaf",
      Sex: "male",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "345498",
      Fare: 7.775,
      Cabin: "None",
    },
    {
      PassengerId: 984,
      Pclass: 1,
      Name: "Davidson, Mrs. Thornton (Orian Hays)",
      Sex: "female",
      Age: 27.0,
      SibSp: 1,
      Parch: 2,
      Ticket: "F.C. 12750",
      Fare: 52.0,
      Cabin: "B71",
    },
    {
      PassengerId: 985,
      Pclass: 3,
      Name: "Guest, Mr. Robert",
      Sex: "male",
      Age: "None",
      SibSp: 0,
      Parch: 0,
      Ticket: "376563",
      Fare: 8.05,
      Cabin: "None",
    },
    {
      PassengerId: 986,
      Pclass: 1,
      Name: "Birnbaum, Mr. Jakob",
      Sex: "male",
      Age: 25.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "13905",
      Fare: 26.0,
      Cabin: "None",
    },
    {
      PassengerId: 987,
      Pclass: 3,
      Name: "Tenglin, Mr. Gunnar Isidor",
      Sex: "male",
      Age: 25.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "350033",
      Fare: 7.7958,
      Cabin: "None",
    },
    {
      PassengerId: 988,
      Pclass: 1,
      Name: "Cavendish, Mrs. Tyrell William (Julia Florence Siegel)",
      Sex: "female",
      Age: 76.0,
      SibSp: 1,
      Parch: 0,
      Ticket: "19877",
      Fare: 78.85,
      Cabin: "C46",
    },
    {
      PassengerId: 989,
      Pclass: 3,
      Name: "Makinen, Mr. Kalle Edvard",
      Sex: "male",
      Age: 29.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "STON/O 2. 3101268",
      Fare: 7.925,
      Cabin: "None",
    },
    {
      PassengerId: 990,
      Pclass: 3,
      Name: "Braf, Miss. Elin Ester Maria",
      Sex: "female",
      Age: 20.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "347471",
      Fare: 7.8542,
      Cabin: "None",
    },
    {
      PassengerId: 991,
      Pclass: 3,
      Name: "Nancarrow, Mr. William Henry",
      Sex: "male",
      Age: 33.0,
      SibSp: 0,
      Parch: 0,
      Ticket: "A./5. 3338",
      Fare: 8.05,
      Cabin: "None",
    },
  ],
];

export var names = ["Housing Dataset", "Titanic"];

const createSelectItems = () => {
  let items = [];
  for (let i = 0; i < names.length; i++) {
    items.push(
      <Dropdown.Item href={"#/" + names[i]}>{names[i]}</Dropdown.Item>
    );
  }
  return items;
};

export var options = createSelectItems();

export const uploadDataset = (dataset, dataname) => {
  data.push(dataset);
  names.push(dataname);

  console.log("dataset", data);
  console.log("names", names);
};

export const get_data = () => {
  return data;
};

export const get_names = () => {
  return names;
};

export const get_options = () => {
  return createSelectItems();
};
